$(".header-logobar--small").prependTo(".header-top-wrapper");

function injectStyles(rule) {
var div = $("<div />", {
html: '<style>' + rule + '</style>'
}).appendTo("body");
}

injectStyles('.header-top-wrapper { box-shadow: 0 .5rem 1rem 0 rgba(0,0,0,0.15), 0 -.5rem .3rem -1rem #fff; padding: 1rem 1rem .5rem; position: fixed; width: 100%; z-index: 10; } .page-article .col.article__sidebar.article__sidebar-sticky-top { margin-left: 76.7rem; margin-top: 3rem; max-width: 38.1rem; } .page-article .headline, .page-article .breadcrumb, .page-article .social-share, .page-article .facebookLike { margin-left: 0; } .header-logobar.header-logobar--small { margin-right: 1.5rem; } .header-nav-primary__item, .header-nav-overlay-button__label, .header-nav-primary+.header-nav-overlay-button .component-content:before { line-height: 3rem; } .header-logobar.header-logobar--small, .header-nav-primary { margin-bottom: 0; margin-top: 0; } .header-nav-global.premium-mode { float: left; } .header-headline-wrapper { padding-top: 5.5rem; } .header-nav-primary+.header-nav-overlay-button { margin-bottom: 0; margin-top: -.1rem; } .page-article .col.article__sidebar { margin-top: 5rem; } @media only screen and (min-width: 1008px) { .page-article.container, .header-headline-wrapper, .header-nav-local .component-content { width: 115rem; } } .header-nav-global.premium-mode .header-nav-global__item:nth-child(n+4) { display: none; } @media only screen and (min-width: 1050px) { .header-nav-global.premium-mode .header-nav-global__item:nth-child(n+4) { display: block; } } .header-nav-primary--short { display: none; } @media only screen and (min-width: 810px) { .header-nav-primary--short { display: inline-block; } } .snippet-header { padding-top: 0; } .article-body-text p { margin-bottom: 2rem; } @media only screen and (min-width: 1008px) { .page-article .article-body-image[data-frz-ratio^="1."] figure, .page-article .lead-asset img[data-frz-ratio^="1."] { max-width: 653px; } }');
